### PR TITLE
Tradotte props aggiuntive

### PR DESCRIPTION
**Pull request by parroit**
https://github.com/iojs/website/pull/258

### CODE REVIEW

**Comment by hex7c0** [comment]
mmm `Lingue` non mi convince
forse `Localizzazioni`?

**Comment by parroit** [comment]
Sì, meglio!

**Comment by hex7c0** [comment]
:+1:

**Comment by parroit** [comment]
Ti occupi tu di fare un PR?

**Comment by hex7c0** [comment]
okay @parroit 
lo farò in serata

**Comment by parroit** [comment]
:+1:

**Comment by hex7c0** [comment]
landed in https://github.com/iojs/website/pull/274
sistemiamo i markdown con i tag delle versioni e facciamo il merge

**Comment by parroit** [comment]
L'ho già fatto ieri sera, trovi i file con i tag nel branch website. Non ho ancora fatto PR su master perchè non ho ancora provato il processo di build. Inoltre non ho capito se il nuovo processo di build è già attivo, @snostorm ha citato files che sono nel branch template-build-refactor_i18n-footer. Nel master mi sembra che non siano ancora presenti i tag...

**Comment by hex7c0** [comment]
si infatti aspettiamo che sia definitivo e poi facciamo il merge

**Comment by snostorm** [comment]
Hi, I'm doing my best off of Google Translate -- the i18n footer stuff is all merged now so the new build process should work for you. Any specific questions? 

_Spiacente, non parlo italiano_ :)

**Comment by parroit** [comment]
It look you do, @snostorm  :-)  We are talking here about the introduction of current version variables. Are the build feature merged by now, or are you referring only to new language links on footer?

**Comment by snostorm** [comment]
The "current version" variables went live with the content updates for v1.4.2/v1.4.3 a few days ago. So yes, it is safe to use these.

The language links (including the word "Languages") and hidden comment easter egg are also live.

The English markdown files and `template.json` in **website#master** are good indicators of what is supported.
- https://raw.githubusercontent.com/iojs/website/master/content/en/index.md
- Some additional variables are starting to become available (also in handlebars) via https://github.com/iojs/website/blob/master/source/project.js

We'll document this more shortly as there is a lot of new helpful stuff very close to being merged.

**Comment by parroit** [comment]
:+1: thank you

**Comment by snostorm** [comment]
If you want a sneak peek of more future stuff, see https://github.com/iojs/website/pull/276

**Comment by hex7c0** [comment]
hey @snostorm sorry for delay
thanks so much

**Pull request merged**
